### ISSUE TITLE
Crash Test

### ISSUE THREAD

**Issue by lmangani** [quackscience/duckdb-extension-clickhouse-native#1]
The application is very immature and crashes on several occasions:

- segfault on file open (?!?)
- segfault on large files - [we dont correctly parse the size of the header with column/row count](https://github.com/quackscience/duckdb-extension-clickhouse-native/blob/main/src/lib.rs#L109)

### Download Duckd
```
wget https://github.com/duckdb/duckdb/releases/download/v1.1.3/duckdb_cli-linux-amd64.zip && unzip duckdb_cli-linux-amd64.zip
./duckdb -unsigned
```

### Build Extension
```bash
cd /usr/src
git clone --recurse-submodules https://github.com/quackscience/duckdb-extension-clickhouse-native
cd duckdb-extension-clickhouse-native
make configure
make debug
```

### Dev file
A basic file always succeeds.
```
clickhouse local -q "SELECT version(), number FROM numbers(1) INTO OUTFILE 'test.clickhouse' FORMAT Native;"
```
```sql
D LOAD '/usr/src/duckdb-extension-clickhouse-native/build/debug/clickhouse_native.duckdb_extension';
D SELECT * FROM clickhouse_native('/tmp/test.clickhouse');
┌──────────────┬─────────┐
│  version()   │ number  │
│   varchar    │ varchar │
├──────────────┼─────────┤
│ 24.12.1.1273 │ 0       │
└──────────────┴─────────┘
```

### Crash Test
Generate some series with clickhouse-local and try to load them incrementally, 100, 1000, 10000
```bash
clickhouse local -q "SELECT * FROM numbers(100) INTO OUTFILE '/tmp/100.clickhouse' FORMAT Native;"
```

#### DuckDB Reader
```bash
duckdb -unsigned
```
```sql
D LOAD '/usr/src/duckdb-extension-clickhouse-native/build/debug/clickhouse_native.duckdb_extension';
D SELECT * FROM clickhouse_native('/tmp/100.clickhouse');
```

### Errors
```
D SELECT * FROM clickhouse_native('/tmp/100000.clickhouse');
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/duckdb-1.1.1/src/vtab/function.rs:32:47:
called `Result::unwrap()` on an `Err` value: NulError(15, [3, 6, 110, 117, 109, 98, 101, 114, 6, 85, 73, 110, 116, 54, 52, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 0, 0, 0, 0, 18, 0, 0, 0, 0, 0, 0, 0, 19, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 0, 0, 22, 0, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 25, 0, 0, 0, 0, 0, 0, 0, 26, 0, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0, 0, 0, 0, 28, 0, 0, 0, 0, 0, 0, 0, 29, 0, 0, 0, 0, 0, 0, 0])
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x7fc5364ec88a - std::backtrace_rs::backtrace::libunwind::trace::h5a5b8284f2d0c266
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7fc5364ec88a - std::backtrace_rs::backtrace::trace_unsynchronized::h76d4f1c9b0b875e3
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fc5364ec88a - std::sys::backtrace::_print_fmt::hc4546b8364a537c6
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/sys/backtrace.rs:66:9
   3:     0x7fc5364ec88a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h5b6bd5631a6d1f6b
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/sys/backtrace.rs:39:26
   4:     0x7fc536508303 - core::fmt::rt::Argument::fmt::h270f6602a2b96f62
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/fmt/rt.rs:177:76
   5:     0x7fc536508303 - core::fmt::write::h7550c97b06c86515
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/fmt/mod.rs:1186:21
   6:     0x7fc5364ea883 - std::io::Write::write_fmt::h7b09c64fe0be9c84
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/io/mod.rs:1839:15
   7:     0x7fc5364ec6d2 - std::sys::backtrace::BacktraceLock::print::h2395ccd2c84ba3aa
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/sys/backtrace.rs:42:9
   8:     0x7fc5364ed5ac - std::panicking::default_hook::{{closure}}::he19d4c7230e07961
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:268:22
   9:     0x7fc5364ed3f2 - std::panicking::default_hook::hf614597d3c67bbdb
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:295:9
  10:     0x7fc5364edb87 - std::panicking::rust_panic_with_hook::h8942133a8b252070
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:801:13
  11:     0x7fc5364ed9e6 - std::panicking::begin_panic_handler::{{closure}}::hb5f5963570096b29
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:667:13
  12:     0x7fc5364ecd69 - std::sys::backtrace::__rust_end_short_backtrace::h6208cedc1922feda
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/sys/backtrace.rs:170:18
  13:     0x7fc5364ed6ac - rust_begin_unwind
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
  14:     0x7fc5364a1c4d - core::panicking::panic_nounwind_fmt::runtime::h1f507a806003dfb2
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:112:18
  15:     0x7fc5364a1c4d - core::panicking::panic_nounwind_fmt::h357fc035dc231634
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:122:5
  16:     0x7fc5364a1ce2 - core::panicking::panic_nounwind::hd0dad372654c389a
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:221:5
  17:     0x7fc5364a1e45 - core::panicking::panic_cannot_unwind::h65aefd062253eb19
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:310:5
  18:     0x7fc5364aad20 - duckdb::vtab::bind::hfc8652160491836d
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/duckdb-1.1.1/src/vtab/mod.rs:146:1
  19:          0x15c0920 - _ZN6duckdb18CTableFunctionBindERNS_13ClientContextERNS_22TableFunctionBindInputERNS_6vectorINS_11LogicalTypeELb1EEERNS4_ISsLb1EEE
  20:           0xdeb76d - _ZN6duckdb6Binder25BindTableFunctionInternalERNS_13TableFunctionERKNS_16TableFunctionRefENS_6vectorINS_5ValueELb1EEESt13unordered_mapISsS7_NS_33CaseInsensitiveStringHashFunctionENS_29CaseInsensitiveStringEqualityESaISt4pairIKSsS7_EEENS6_INS_11LogicalTypeELb1EEENS6_ISsLb1EEE
  21:           0xdec897 - _ZN6duckdb6Binder4BindERNS_16TableFunctionRefE
  22:           0xe27595 - _ZN6duckdb6Binder4BindERNS_8TableRefE
  23:          0x164a50c - _ZN6duckdb6Binder8BindNodeERNS_10SelectNodeE
  24:           0xe27e7b - _ZN6duckdb6Binder8BindNodeERNS_9QueryNodeE
  25:           0xe28b1b - _ZN6duckdb6Binder4BindERNS_9QueryNodeE
  26:           0xdb2689 - _ZN6duckdb6Binder4BindERNS_15SelectStatementE
  27:           0xe28a45 - _ZN6duckdb6Binder4BindERNS_12SQLStatementE
  28:           0xe328d2 - _ZN6duckdb7Planner10CreatePlanERNS_12SQLStatementE
  29:           0xb9dff9 - _ZN6duckdb13ClientContext31CreatePreparedStatementInternalERNS_17ClientContextLockERKSsNS_10unique_ptrINS_12SQLStatementESt14default_deleteIS6_ELb1EEENS_12optional_ptrISt13unordered_mapISsNS_18BoundParameterDataENS_33CaseInsensitiveStringHashFunctionENS_29CaseInsensitiveStringEqualityESaISt4pairIS3_SC_EEELb1EEE
  30:           0xb9ee2d - _ZN6duckdb13ClientContext23CreatePreparedStatementERNS_17ClientContextLockERKSsNS_10unique_ptrINS_12SQLStatementESt14default_deleteIS6_ELb1EEENS_12optional_ptrISt13unordered_mapISsNS_18BoundParameterDataENS_33CaseInsensitiveStringHashFunctionENS_29CaseInsensitiveStringEqualityESaISt4pairIS3_SC_EEELb1EEENS_21PreparedStatementModeE
  31:           0xb9f0fc - _ZNSt17_Function_handlerIFvvEZN6duckdb13ClientContext15PrepareInternalERNS1_17ClientContextLockENS1_10unique_ptrINS1_12SQLStatementESt14default_deleteIS6_ELb1EEEEUlvE_E9_M_invokeERKSt9_Any_data
  32:           0xb89fb9 - _ZN6duckdb13ClientContext32RunFunctionInTransactionInternalERNS_17ClientContextLockERKSt8functionIFvvEEb
  33:           0xb8ab25 - _ZN6duckdb13ClientContext15PrepareInternalERNS_17ClientContextLockENS_10unique_ptrINS_12SQLStatementESt14default_deleteIS4_ELb1EEE
  34:           0xba3878 - _ZN6duckdb13ClientContext7PrepareENS_10unique_ptrINS_12SQLStatementESt14default_deleteIS2_ELb1EEE
  35:           0xba392f - _ZN6duckdb10Connection7PrepareENS_10unique_ptrINS_12SQLStatementESt14default_deleteIS2_ELb1EEE
  36:           0x728361 - duckdb_shell_sqlite3_prepare_v2
  37:           0x715e30 - shell_exec
  38:           0x717a40 - runOneSqlLine.constprop.0
  39:           0x71f795 - process_input
  40:           0x6f4267 - main
  41:     0x7fc53655adba - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  42:     0x7fc53655ae75 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  43:           0x6f7fd7 - <unknown>
  44:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
Aborted
```

**Comment by lmangani** [comment]
Resolved
